abstract: RT Extension-MenubarUserTickets Extension
distribution_type: module
generated_by: Module::Install version 0.52
license: Perl
name: RT-Extension-MenubarUserTickets
no_index:
  directory:
    - html
    - inc
    - t
version: 0.01
